name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "CHECKOUT: code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "SETUP: Node.js v22 + yarn"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "yarn"

      - name: "INSTALL: yarn pkgs"
        run: yarn install --frozen-lockfile

      - name: "BUILD: vite build && ssg.ts build"
        run: |
          source .github/workflows/ci-helper.sh
          sep
          info "BUILD INIT"
          info "1-VITE: run vite build"
          yarn build:vite
          info "2-SSG: run ssg.ts build"
          yarn build:ssg
          success "BUILD DONE"

      - name: "CONFIGURE: Git"
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: "DEPLOY: commit dist in production branch"
        run: |
          source .github/workflows/ci-helper.sh
          sep
          info "DEPLOY INIT"
          info "CHECKOUT: production branch"
          git checkout -b production
          info "ADD: dist, wrangler.toml, functions"
          git add -f dist wrangler.toml functions
          info "PRD-COMMIT: sha:${SHA} | ${SUBJECT}/ $DATE"
          SHA=$(git rev-parse --short HEAD)
          SUBJECT=$(git log -1 --pretty=format:'%s')
          info "PUSH: origin production"
          git commit -m "[DEPLOY] sha:${SHA} | ${SUBJECT}"
          git push -f origin production
          success "GA_DONE: Check Cloudflare Pages dashboard for deployment"
